name: DataStructures Example Build
on:
  push:
    paths:
    - 'Examples/DataStructures/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dotnet build
      run: dotnet build Examples/DataStructures/DataStructures.csproj --configuration 'Release'
