name: CommandLine Example Build
on:
  push:
    paths:
    - 'Examples/CommandLine/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dotnet build
      run: dotnet build Examples/CommandLine/CommandLine.csproj --configuration 'Release'
