name: Towel Build
on:
  push:
    paths:
    - 'Sources/Towel/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dotnet build
      run: dotnet build Sources/Towel/Towel.csproj --configuration 'Release'
